# -*- coding: utf-8 -*-
"""PythonOOP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDnqAqMYYYOuwzbkQC_qpXQb0y5sVDXR
"""

# Name Olufunmi Falokun date 2/14/2023
class Car:
    def __init__(self, name):
        # this is the constructor of the car class that is called everytime a new object is created from this class
        # it also assigns a name to the object.
        self.name = name

    def go(self):
        #this method makes this car object to start moving
        print("The " +self.name + " is moving.")    

    def stop(self):
        # this method makes this car object to start stoping.
        print("The " + self.name + " is stoping.")

def main():
    # this is the main method of this program 
    car1 = Car("Chevy") #create new Car object instance car1 with the name Chevy
    car1.go()           #make car1 to start moving
    car1.stop()         #mske car1 to stop moving.
    car2 = Car("Kia")  # create a new car object instancewith the name Kia.
 
    car2.go()           #make car2 to start moving           
    car2.stop()         #mske car2 to stop moving.

    #adding another car
    car3 = Car("Toyota corolla")  # create a new car object instance with the name Toyota Corolla.
    car3.go()           #make car3 to start moving           
    car3.stop()         #mske car3 to stop moving.

if __name__ == "__main__":  #
  main()                #calls the main method